' Gambas module file

'
' Nuevo ciclo
' Interfaz para programa de la terminal
'
' Copyright (C) Martín Belmonte.
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

Public stxProgKey As New String[]
Public stxProgVal As New String[]
Public strAppPath As String
Public strAppName As String
Public stxPackages As New String[]
Public stxLang As New String[][]
Public stxPaper As New String[][]
Public stxOrie As New String[][]
Public stxDay As New String[][]

Public Sub Main()

  Dim stxTmp As New Variant[][]
  Dim intTmp As Integer
  Dim intP As Integer
  Dim intKey As Integer

  strAppPath = User.Home &/ "." & Application.Name

  ' Existencia de directorio de la aplicacion en el directorio home. Esto se ejecutara una unica vez.
  ' Aqui se pueden agregar mas comprobaciones de este tipo para copia de archivos de configuracion y demas cosas similares
  If Exist(strAppPath) = False Then
    Mkdir strAppPath
  Endif
  Wait 0.05
  If Exist(strAppPath &/ "README.md") = False Then
    Copy "README.md" To strAppPath &/ "README.md"
  Endif
  If Exist(strAppPath &/ "logo.png") = False Then
    Copy "logo.png" To strAppPath &/ "logo.png"
  Endif
  If Exist(strAppPath &/ "template.cfg") = False Then
    Copy "template.cfg" To strAppPath &/ "template.cfg"
  Endif

  ' Carga de los parámetros del prgrama conjuntamente con gb.settings./////////////////////////
  stxLang.Clear
  stxLang.Insert(LoadLang())

  stxPaper.Clear
  stxPaper.Insert(LoadPaper())

  stxOrie.Clear
  stxOrie.Insert(LoadOrie())

  stxDay.Clear
  stxDay.Insert(LoadDay())

  If Initiator() = 1 Then
    For intKey = 0 To stxProgKey.Max
      stxProgVal[intKey] = Settings[stxProgKey[intKey], stxProgVal[intKey]]
    Next
  Endif

  Select stxProgVal[7]
    Case "T", "True"
      Select Dependences() ' Estado de las dependencias.
        Case 0
          Message.Info("Algunas caracteristicas no funcionaran hasta que no instale las dependencias")
        Case 1
      End Select
  End Select

  FMain.Show()

End

Public Function Initiator() As Integer  ''Funcion que carga los parámetros por defecto del programa. 1 ok, 0 Matrices iguales pero no se cargo todo -1 matrices distintas

  Dim int As Integer
  Dim intSize As Integer

  For int = 0 To 12

    stxProgKey.Add("")
    stxProgVal.Add("")
  Next

  stxProgKey[0] = "Program/Paper-Size"
  If IsNumber(Settings[stxProgKey[0], ""]) = True Then
    stxProgVal[0] = Settings[stxProgKey[0], ""]
  Else
    stxProgVal[0] = 2
  Endif

  stxProgKey[1] = "Program/Paper-Orientation"
  If IsNumber(Settings[stxProgKey[1], ""]) = True Then
    stxProgVal[1] = Settings[stxProgKey[1], ""]
  Else
    stxProgVal[1] = 1
  Endif
  'stxProgVal[1] = Settings[stxProgKey[1], ""]

  stxProgKey[2] = "Program/Text-Language"
  If IsNumber(Settings[stxProgKey[2], ""]) = True Then
    stxProgVal[2] = Settings[stxProgKey[2], ""]
  Else
    stxProgVal[2] = 21
  Endif
  'stxProgVal[2] = Settings[stxProgKey[2], ""]

  stxProgKey[3] = "Program/First-Day"
  If IsNumber(Settings[stxProgKey[3], ""]) = True Then

    stxProgVal[3] = Settings[stxProgKey[3], ""]
  Else
    stxProgVal[3] = 0
  Endif

  stxProgVal[3] = Settings[stxProgKey[3], ""]

  stxProgKey[4] = "Program/Font-Type-1"
  stxProgVal[4] = Settings[stxProgKey[4], "Times-Roman/18"]

  stxProgKey[5] = "Program/Font-Type-2"
  stxProgVal[5] = Settings[stxProgKey[5], "Times-Roman/30"]

  stxProgKey[6] = "Program/Font-Type-3"
  stxProgVal[6] = Settings[stxProgKey[6], "Times-Roman/10"]

  stxProgKey[7] = "Program/File-cfg"
  stxProgVal[7] = Settings[stxProgKey[7], strAppPath &/ "template.cfg"]

  stxProgKey[8] = "Program/Application-Path"
  stxProgVal[8] = Settings[stxProgKey[8], strAppPath]

  stxProgKey[9] = "Program/Year"
  stxProgVal[9] = Settings[stxProgKey[9], ""]

  stxProgKey[10] = "Program/Month-Init"
  stxProgVal[10] = Settings[stxProgKey[10], ""]

  stxProgKey[11] = "Program/Month-Qty"
  stxProgVal[11] = Settings[stxProgKey[11], ""]

  stxProgKey[12] = "Program/Last-Directory"
  stxProgVal[12] = Settings[stxProgKey[12], ""]

  If stxProgKey.Max = stxProgVal.Max Then
    Return 1
  Else
    Return 0
  Endif

End

Public Function LoadLang() As String[][] ''Carga las listaas de lenguajes disponibles.

  Dim stx As New String[][]

  stx.Add(["catalan", ("Catalán"), "ca"])
  stx.Add(["czech", ("Checo"), "cs"])
  stx.Add(["danish", ("Danés"), "da"])
  stx.Add(["dutch", ("Holandés"), "nl"])
  stx.Add(["english", ("Inglés"), "en"])
  stx.Add(["esperanto", ("Esperanto"), "eo"])
  stx.Add(["estonian", ("Estonio"), "et"])
  stx.Add(["finnish", ("Finlandés"), "fi"])
  stx.Add(["french", ("Francés"), "fr"])
  stx.Add(["german", ("Alemán"), "de"])
  stx.Add(["greek", ("Griego"), "el"])
  stx.Add(["hawaiian", ("Hawaiano"), "haw"])
  stx.Add(["hungarian", ("Húngaro"), "hu"])
  stx.Add(["italian", ("Italiano"), "it"])
  stx.Add(["latvian", ("Letón"), "lv"])
  stx.Add(["lithuanian", ("Lituano"), "lt"])
  stx.Add(["polish", ("Polaco"), "pl"])
  stx.Add(["portuguese", ("Portugués"), "pt"])
  stx.Add(["romanian", ("Rumano"), "ro"])
  stx.Add(["russian", ("Ruso"), "ru"])
  stx.Add(["slovak", ("Eslovaco"), "sk"])
  stx.Add(["spanish", ("Español"), "es"])
  stx.Add(["swedish", ("Sueco"), "sv"])
  stx.Add(["ukrainian", ("Ucraniano"), "uk"])

  Return stx

End

Public Function LoadPaper() As String[][] ''Carga la lista de formatos de hojas.

  Dim stx As New String[][]

  stx.Add(["letter", ("Carta"), "215.9 × 279.4"])
  stx.Add(["legal", ("Legal"), "215.9 × 355.6"])
  stx.Add(["a4", ("A4"), "210 × 297"])
  stx.Add(["tabloid", ("Doble carta"), "279.4 × 431.8"])

  Return stx

End

Public Function LoadOrie() As String[][] ''Carga la lista de orientaciones de las hojas.

  Dim stx As New String[][]

  stx.Add(["portait", ("Retrato"), "0º"])
  stx.Add(["landscape", ("Apaisada"), "90º"])

  Return stx

End

Public Function LoadDay() As String[][] ''Carga la lista de dias suceptibles de ser el inicio de la semana.

  Dim stx As New String[][]

  stx.Add(["monday", ("Lunes"), "0"])
  stx.Add(["sunday", ("Domingo"), "6"])

  Return stx

End

Public Function Dependences() As Integer ''Analisis de dependencias, si hay paquetes que falta instalar se procede a instalarlos y la funcion retorna la cantidad remanente de paquetes, siendo cero si se instalaron todos.

  Dim str As String
  Dim strCmm As String

  str &= ("Debes instalar los siguientes paquetes") & ":\n"

  Select GEFSys.Distro()

    Case "debian", "ubuntu", "mint"
      strCmm = "sudo apt-get install "
      If Exist("dep-deb.txt") = True Then
        stxPackages = GEFUtility.FileLoad("dep-deb.txt")
      Endif
    Case "manjaro", "arch"
      strCmm = "sudo pacman -S "
      If Exist("arc.txt") = True Then
        stxPackages = GEFUtility.FileLoad("arc.txt")
      Else
        If Exist("dep-deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("dep-deb.txt")
        Endif
      Endif
    Case "fedora", "redhat"
      strCmm = "sudo dnf install "
      If Exist("rht.txt") = True Then
        stxPackages = GEFUtility.FileLoad("rht.txt")
      Else
        If Exist("dep-deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("dep-deb.txt")
        Endif
      Endif

    Case "gentoo"
      strCmm = "sudo emerge -a "
      If Exist("gto.txt") = True Then
        stxPackages = GEFUtility.FileLoad("gto.txt")
      Else
        If Exist("dep-deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("dep-deb.txt")
        Endif
      Endif

    Case "suse", "opensuse"
      strCmm = "sudo zipper install "
      If Exist("osu.txt") = True Then
        stxPackages = GEFUtility.FileLoad("osu.txt")
      Else
        If Exist("dep-deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("dep-deb.txt")
        Endif
      Endif

  End Select

  If stxPackages.Count > 0 Then
    stxPackages = GEFSys.PkgDep(stxPackages)
    If stxPackages.Count > 0 Then ' Existen paquete que no estan instalados

      File.Save("/tmp/apt.txt", str & strCmm & stxPackages.Join(" "))
      Wait 1
      Desktop.Open("/tmp/apt.txt")

    Endif
  Endif
  Return stxPackages.Count

End

Public Function Savior() As String[] ''Funcion que guarda las configuraciones que se modificaron en el programa.

  Dim int As Integer
  Dim stx As New String[]

  For int = 0 To stxProgKey.Max
    Select Settings[stxProgKey[int]]
      Case stxProgVal[int]
      Case Else
        Settings[stxProgKey[int]] = stxProgVal[int]
        stx.Add(stxProgKey[int] & ": " & stxProgVal[int])
    End Select
  Next
  Return stx

End

Public Function Terminator() As Integer ''Funcion que guarda las configuraciones que se modificaron en el programa antes de cerrarlo.

  Dim int As Integer
  ' Guardando los parámetros del programa
  For int = 0 To stxProgKey.Max
    Settings[stxProgKey[int]] = stxProgVal[int]
    Print "Guardando: " & stxProgKey[int] & ": " & stxProgVal[int]
  Next

  Settings.Save

  Return 1

End
